import { AppContextProvider } from '@/context/app.context'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/nav'
import Player from '@/components/player'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppContextProvider>
                    <Nav />
                    {children}
                    <Player />
                </AppContextProvider>
            </body>
        </html>
    )
}
